#!/usr/bin/env bash
#
# tests/test-install-hooks-readiness.sh — typed hook-readiness predicate.
#
# Issue #515 acceptance: hook readiness must be TYPED, not inferred from the
# generic pre-commit.com marker. A pre-commit shim copied over pre-push still
# carries the marker but runs `--hook-type pre-commit`, silently bypassing
# every pre-push validation. These fixtures pin the predicate contract that
# doctor and the first-push gate share:
#   1. correct shims          → ready
#   2. copied wrong type      → NOT ready (fails on the untyped predicate)
#   3. inert file (no marker) → NOT ready
#   4. missing file           → NOT ready
#   5. non-executable shim    → NOT ready
#   6. linked worktree        → resolves shared hooks and reports ready
#   7. core.hooksPath         → resolves the configured path
#
set -euo pipefail

TOUCHSTONE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=../lib/install-hooks.sh
source "$TOUCHSTONE_ROOT/lib/install-hooks.sh"

TMPROOT="$(mktemp -d -t touchstone-test-hook-readiness.XXXXXX)"
trap 'rm -rf "$TMPROOT"' EXIT

ERRORS=0

fail() {
  echo "FAIL: $*" >&2
  ERRORS=$((ERRORS + 1))
}

mk_repo() {
  local dir="$TMPROOT/$1"
  mkdir -p "$dir"
  git -C "$dir" init -q -b main
  git -C "$dir" config user.email t@e.co
  git -C "$dir" config user.name Test
  : >"$dir/.keep"
  git -C "$dir" add .keep
  git -C "$dir" commit -q -m init
  printf '%s' "$dir"
}

# Writes a realistic pre-commit-framework shim for the given hook type.
write_shim() {
  local path="$1" hook_type="$2"
  cat >"$path" <<EOF
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=${hook_type})
exec echo "fake shim"
EOF
  chmod +x "$path"
}

# Case 1: correctly typed shims in both slots → ready.
R1="$(mk_repo case1)"
write_shim "$R1/.git/hooks/pre-commit" pre-commit
write_shim "$R1/.git/hooks/pre-push" pre-push
if ! touchstone_project_hooks_ready "$R1"; then
  fail "case 1: correctly typed shims must report ready"
fi

# Case 2: pre-commit shim copied over the pre-push slot. Marker present,
# executable, but the shim runs --hook-type pre-commit — pre-push validation
# is silently bypassed. Must NOT be ready.
R2="$(mk_repo case2)"
write_shim "$R2/.git/hooks/pre-commit" pre-commit
write_shim "$R2/.git/hooks/pre-push" pre-commit
if touchstone_project_hooks_ready "$R2"; then
  fail "case 2: wrong-typed pre-push shim must not report ready"
fi
if touchstone_pre_commit_hook_ready "$R2/.git/hooks/pre-push" pre-push; then
  fail "case 2: predicate accepted a pre-commit shim occupying the pre-push slot"
fi

# Case 3: inert file — executable, right name, no framework marker.
R3="$(mk_repo case3)"
printf '#!/bin/sh\nexit 0\n' >"$R3/.git/hooks/pre-commit"
chmod +x "$R3/.git/hooks/pre-commit"
write_shim "$R3/.git/hooks/pre-push" pre-push
if touchstone_project_hooks_ready "$R3"; then
  fail "case 3: inert pre-commit hook must not report ready"
fi

# Case 4: missing file.
R4="$(mk_repo case4)"
write_shim "$R4/.git/hooks/pre-commit" pre-commit
if touchstone_project_hooks_ready "$R4"; then
  fail "case 4: missing pre-push hook must not report ready"
fi
if touchstone_project_hooks_present "$R4"; then
  fail "case 4: hooks-present must be false when a slot is empty"
fi

# Case 5: correct content but not executable — Git silently skips it.
R5="$(mk_repo case5)"
write_shim "$R5/.git/hooks/pre-commit" pre-commit
write_shim "$R5/.git/hooks/pre-push" pre-push
chmod -x "$R5/.git/hooks/pre-push"
if touchstone_project_hooks_ready "$R5"; then
  fail "case 5: non-executable pre-push hook must not report ready"
fi

# Case 6: linked worktree — hooks live in the primary checkout's common git
# dir; the predicate must resolve them from the linked worktree and report
# ready there (the false negative that opened issue #515).
R6="$(mk_repo case6)"
write_shim "$R6/.git/hooks/pre-commit" pre-commit
write_shim "$R6/.git/hooks/pre-push" pre-push
R6_WT="$TMPROOT/case6-linked"
git -C "$R6" worktree add -q -b feature/linked "$R6_WT"
if ! touchstone_project_hooks_ready "$R6_WT"; then
  fail "case 6: linked worktree must resolve shared hooks as ready"
fi
R6_RESOLVED="$(touchstone_git_hook_path "$R6_WT" pre-push)"
# macOS tmpdirs symlink /var → /private/var, so compare by suffix: the
# resolved path must land in the PRIMARY checkout's git dir, not the linked
# worktree's private dir.
case "$R6_RESOLVED" in
  */case6/.git/hooks/pre-push | */case6/.git/worktrees/*) ;;
  *) fail "case 6: unexpected resolved pre-push path: $R6_RESOLVED" ;;
esac

# Case 7: core.hooksPath — the effective hook location is the configured
# directory, not .git/hooks.
R7="$(mk_repo case7)"
mkdir -p "$R7/custom-hooks"
git -C "$R7" config core.hooksPath custom-hooks
write_shim "$R7/custom-hooks/pre-commit" pre-commit
write_shim "$R7/custom-hooks/pre-push" pre-push
if ! touchstone_project_hooks_ready "$R7"; then
  fail "case 7: core.hooksPath shims must report ready"
fi
R7_RESOLVED="$(touchstone_git_hook_path "$R7" pre-commit)"
case "$R7_RESOLVED" in
  */custom-hooks/pre-commit) ;;
  *) fail "case 7: resolution must honor core.hooksPath, got: $R7_RESOLVED" ;;
esac

# Case 8: typed shim bound to an ALTERNATE config. The marker and hook type
# match, but the shim runs `--config other.yaml`, so none of this project's
# validation executes. Must NOT be ready.
R8="$(mk_repo case8)"
cat >"$R8/.git/hooks/pre-commit" <<'EOF'
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
ARGS=(hook-impl --config=other.yaml --hook-type=pre-commit)
exec echo "fake shim"
EOF
chmod +x "$R8/.git/hooks/pre-commit"
write_shim "$R8/.git/hooks/pre-push" pre-push
if touchstone_project_hooks_ready "$R8"; then
  fail "case 8: shim bound to an alternate config must not report ready"
fi
if touchstone_pre_commit_hook_ready "$R8/.git/hooks/pre-commit" pre-commit; then
  fail "case 8: predicate accepted a shim running a non-Touchstone config"
fi

if [ "$ERRORS" != 0 ]; then
  echo "==> FAIL: $ERRORS hook-readiness case(s) regressed" >&2
  exit 1
fi
echo "==> PASS: typed hook-readiness predicate holds across fixture classes"
